blm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blm import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^chris/', include('chris.urls', namespace='chris')),
    url(r'^sprout/', include('sprout.urls', namespace='sprout')),
]

chris/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^index/$', login, {'template_name': 'chris/index.html'}, name="login"),
    url(r'^logout/$', logout, {'next_page': '../'}, name="logout"),
    url(r'^register/$', views.register, name='register'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
     views.activate, name='activate'),
    url(r'^menu/$', views.menu, name="menu"),
    url(r'^settings/$', views.settings, name="settings"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^change_password/$', views.change_password, name="change_password"),
    url(r'^reset_password/$', password_reset,{'template_name':
    'chris/reset_password.html', 'post_reset_redirect':
    'chris:password_reset_done', 'email_template_name':
    'chris/reset_password_email.html'}, name="reset_password"), # See tutorial 31

    url(r'^password_reset/done/$', password_reset_done, {'template_name':
    'chris/reset_password_done.html'}, name="password_reset_done"),

    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, {'template_name':
    'chris/reset_password_confirm.html', 'post_reset_redirect':
    'chris:password_reset_complete'}, name="password_reset_confirm"),

    url(r'^password_reset/complete/$', password_reset_complete, {'template_name':
    'chris/reset_password_complete.html'}, name="password_reset_complete"),
]

chris/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from datetime import date

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    email = models.CharField(max_length=32, default='')
    phone = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

class Budget(models.Model):

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    user = models.ForeignKey(User)
    title = models.CharField(max_length=30, default='') # name of budget
    amount = models.IntegerField(default=0) # total amount to be set aside
    mode = models.NullBooleanField() # all at once or multiple disbursements
    interval = models.IntegerField(default=0) # days between disbursements
    frequency = models.IntegerField(default=0) # days(1), weeks(2), months(3), 30 days(4), year(5)
    freq_factor = models.IntegerField(default=0) # frequency factor or constant
    pay_value = models.IntegerField(default=0) # amount to be paid at individual disbursement
    pay_qty = models.IntegerField(default=0) # qty of individual disbursements
    pay_count = models.IntegerField(default=0) # count of last disbursement
    next_date = models.DateField(blank=False, null=False) # date of next disbursement to be made
    final_date = models.DateField(null=False, blank=True) # date of last disbursement
    budget_status = models.IntegerField(default=0) # 0=unpaid, 1=paid, 2=disbursement started, 3=disbursement complete, 4=other
    pay_ref = models.CharField(max_length=30, null=True) # Payment reference for funding a budget
    pay_status = models.CharField(max_length=10, null=True) # Status of payment attempt
    amount_funded = models.IntegerField(null=True) # amount funded for budget
    recipient = models.ForeignKey("Bank", blank=True, null=True) # actual account/destination budget is spent on
    recipient_code = models.CharField(max_length=20, blank=False) # required by Paystack
    created = models.DateTimeField(null=False)
    updated = models.DateTimeField(null=False)

class Bank(models.Model):
    def __unicode__(self):
        return self.holder_name, self.bank

    def __str__(self):
        return self.holder_name, self.bank

    holder_name = models.CharField(max_length=55, default="") # The account holder's name
    bank = models.CharField(max_length=55, default="") # The name of the bank
    bank_code = models.CharField(max_length=4, blank=True) # This used to be an IntegerField but ALAT code, 035A contains a character
    acc_no = models.CharField(max_length=10, blank=True) # The recipient (bank) account number
    created = models.DateTimeField(null=False)
    recipient_code = models.CharField(max_length=20, blank=False) # required by Paystack
    user = models.ForeignKey(User)

class Token(models.Model):
    def __unicode__(self):
        return self.user, self.last_4

    def __str__(self):
        return self.user, self.last_4
    last_4 = models.CharField(max_length=4, default='0000') # last 4 digits of card for reccognition
    auth_code = models.CharField(max_length=20, blank=True) #auth code to charge previously charged cards
    card_scheme = models.CharField(max_length=10, blank=True) # Card scheme of card e.g. Visa, MC, Verve
    user = models.ForeignKey(User)

chris/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# from django.contrib.auth.forms import AuthenticationForm
# from django.forms.widgets import PasswordInput, TextInput

# The fields in this form are not in the model
# See tutorial 16 Max Goodridge Django tutorials
#
class RegistrationForm(UserCreationForm):
    # These widgets below work. I just didn't need them
    # email = forms.EmailField(widget=forms.TextInput, label="Email")
    # password1 = forms.CharField(widget=forms.PasswordInput, label="Password")
    # password2 = forms.CharField(widget=forms.PasswordInput, label="Password (again)")

    email = forms.EmailField(required=True)
    password2 = None
#
    class Meta:
        model = User
        fields = (
            # 'username',
            # 'first_name',
            # 'last_name',
            'email',
            'password1',
            # 'password2'
        )

    # def clean(self):
    #     password1 = self.cleaned_data.get("password1")
    #     try:
    #         password_validation.validate_password(password1, self.instance)
    #     except forms.ValidationError as error:
    #
    #         # Method inherited from BaseForm
    #         self.add_error("password1", error)
    #     return password1

    # def clean(self):
    #     cleaned_data = super(RegistrationForm, self).clean()
    #     if "password" in self.cleaned_data and "password2" in self.cleaned_data:
    #         if self.cleaned_data["password1"] != self.cleaned_data["password2"]:
    #             print "there was an error"
    #             raise forms.ValidationError("Passwords do not match. Please enter both fields again")
    #     return self.cleaned_data

    # Deleting password 2 below because I don't know how to solve the
    # ValueError situation when passwords don't match.

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        # user.first_name = self.cleaned_data['first_name']
        # user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.username = user.email

        if commit:
            user.save()

        return user

# Used with AuthenticationForm
# class CustomAuthForm(AuthenticationForm):
#     username = forms.CharField(widget=TextInput(attrs={"class":"validate", "placeholder": "Email"}))
#     password = forms.CharField(widget=PasswordInput(attrs={"placeholder": "Password"}))

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "last_name",
            "password",
        )

chris/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals # Has to be the first thing

# From registration email medium tutorial
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token


from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
# UserCreationForm - no longer required
from chris.forms import EditProfileForm, RegistrationForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, EmailMessage
from django.urls import reverse
# import json

def login_redirect(request):
    # first two optoins don't work on their own. Should you always
    # use redirect with render?
    # return reverse("login")
    # return reverse("chris:login")
    return redirect(reverse("chris:login"))

def index(request):
    return reverse("login")

def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            user.is_active = False
            try:
                user.save()
            except:
                form = RegistrationForm()
                context = {
                    "form": form,
                    "message": "User already exists",
                    }
                return render(request, 'chris/register.html', context)

            current_site = get_current_site(request)
            mail_subject = "Activate your BLM account."
            message = render_to_string("acc_active_email.html", {
            "user": user,
            "domain": current_site.domain,
            "uid":urlsafe_base64_encode(force_bytes(user.pk)),
            "token":account_activation_token.make_token(user),
            })
            email_from = 'welcome@budgetlikemagic.com'
            to_email = form.cleaned_data.get("email")
            send_mail(
                mail_subject,
                message,
                email_from,
                [to_email,],
                fail_silently=False,
            )
            context = {
                "message": "Please confirm your email address to complete registration"
            }
            return render(request, 'chris/register.html', context)
            # return render(request, 'chris/register.html')
    else:
        form = RegistrationForm()

        context = {'form': form}
        return render(request, 'chris/register.html', context)

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)

        context = {
            "message": "email confirmed. Login now",
        }
        return render(request, 'chris/index.html', context)
    else:
        context = {
            "message": "Activation link is invalid",
        }
        return render(request, 'sprout/home.html')


def menu(request):
    return render(request, 'chris/menu.html')

def profile(request):
    context = {
        "user": request.user
    }
    return render(request, 'chris/profile.html', context)

def settings(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse("chris:profile"))
    else:
        form = EditProfileForm(instance=request.user)
        context = {
            "form": form
        }
        return render(request, 'chris/settings.html', context)

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse("chris:profile"))
        else:
            return redirect(reverse("chris:change_password"))
    else:
        form = PasswordChangeForm(user=request.user)
        context = {
            "form": form
        }
        return render(request, 'chris/change_password.html', context)

chris/templates/chris/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Change Password</title>
{% endblock %}

{% block body %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Update</button>
</form>
{% endblock %}

chris/templates/chris/index.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<div v-if="index" id="index">
  <div class="index-title">
    <h1>Budget Like Magic</h1>
  </div>
  <div class="identity">
  <!-- <div class="identity identity-space"> -->
  {{ message }}
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Log In</button>
    </form>
    <!-- <input type="text" name="" value="" placeholder="Email address">
    <input type="password" name="" value="" placeholder="Password"> -->
    <p class="forgot-password">
      <a href="{% url 'chris:reset_password' %}">Forgot Password?</a>
    </p>
    <!-- <button type="submit">Log In</button> -->
    <p><a href="{% url 'chris:register' %}">Don't have an account? Register</a></p>
  </div>
  <div class="index-footer">
  </div>
</div>
{% endblock %}

chris/templates/chris/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<p>{{user}}</p>
<p>{{user.first_name}}</p>
<p>{{user.last_name}}</p>
<p>{{user.email}}</p>
{% endblock %}

chris/templates/chris/register.html
{% extends 'base.html' %}

{% block head %}
<title>Signup</title>
{% endblock %}

{% block body %}
<div id="index">
  <div class="index-title">
    <h1>Budget Like Magic</h1>
    <!-- <p>Register here</p> -->
  </div>
  <div class="identity">
    {{ message }}
    <form method="post" class="reg-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Sign Up</button>
    </form>
    <p class="p-register"><a href="{% url 'chris:login' %}">Already have an account? Login</a></p>
  </div>
</div>
{% endblock %}

chris/templates/chris/reset_password.html
{% extends 'base.html' %}

{% block head %}
<title>Reset Password</title>
{% endblock %}
{% block body %}
<div id="index">
  <h3>Forgotten your password?</h3>
  <span>Enter your Budget-Like-Magic email-address below,<br> and we'll send instructions to create a new one.</span>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset password</button>
  </form>
  <p><a href="{% url 'chris:login' %}">Back to login</a></p>
</div>
{% endblock %}

chris/templates/chris/reset_password_complete.html
{% extends 'base.html' %}

{% block head %}
<title>Password reset complete</title>
{% endblock %}

{% block body %}
<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
<a href="{% url "chris:login" %}">Login</a>
{% endblock %}

chris/templates/chris/reset_password_confirm.html
{% extends 'base.html' %}

{% block head %}
<title>Enter new password</title>
{% endblock %}

{% block body %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Reset password</button>
</form>
{% endblock %}

chris/templates/chris/reset_password_done.html
{% extends 'base.html' %}

{% block head %}
<title>Password reset sent</title>
{% endblock %}

{% block body %}
<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
{% endblock %}

chris/templates/chris/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'chris:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

chris/templates/chris/settings.html
{% extends 'base.html' %}

{% block head %}
<title>settings</title>
{% endblock %}

{% block body %}

<section class="fence">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>

  <div id="title-block">
    <h2>Settings</h2>
  </div>
  <div id="main">

    <!-- <div class="gap">
    </div> -->
    <div class="q-block">
      <label class="bank">
        Password
      </label>
    </div>
    <div class="q-block">
      <label class="bank">
        Pocket Money <span>(every two weeks | Thursday)</span>
        <p class="acc-name">&#8358; 20,000 | 3 of 5</p>
      </label>
    </div>
  </div>
</section>
{% endblock %}